runtime: nodejs
env: standard

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

# Manual scaling and resources configuration
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

env_variables:
  NODE_ENV: production