runtime: nodejs20

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 5

env_variables:
  NODE_ENV: 'production'
  PORT: 8080
handlers:
  - url: /.*
    script: auto
